name: ArtifactAndPackageCustomTaskActions

on:
  workflow_dispatch:

jobs:
  ArtifactAndPackage:
      name: ArtifactAndPackage
      runs-on: ubuntu-latest
      steps:  
        - name: Register Artifact
          uses: ServiceNow/servicenow-devops-register-artifact@v1.34.2
          with:
            devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
            devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'ArtifactAndPackage'
            artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'

        - name: Register Package
          uses: ServiceNow/servicenow-devops-register-package@v1.34.2
          with:
            devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
            devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'ArtifactAndPackage'
            artifacts: ' [{"name": "com:autoclaim","version": "1.${{ github.run_number }}","semanticVersion": "1.${{ github.run_number }}.0","repositoryName": "${{ github.repository }}"}]'
            package-name: 'autoclaim.war'
