name: CustomChangeAction

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Custom Change
        uses: ServiceNow/servicenow-devops-change@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: '{"autoCloseChange":true,"attributes":{"chg_model": {"name": "Normal" },"short_description":"Automated Software Deployments","description":"Automated Software Deployment.","assignment_group":"0a52d3dcd7011200f2d224837e6103f2","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed."}}'
          interval: '100'
          timeout: '3600'
          
      - name: Run deployment scripts
        run: echo Completed Deployment.
  # getchange:
  #   # jobs that  must complete successfully before this job will run
  #   needs: deploy
  #   # type of machine to run the job on
  #   runs-on: ubuntu-latest
  #   name: 'ServiceNow DevOps Get Change'
  #   outputs:
  #     change-request-number: ${{ steps.get_change.outputs.change-request-number }}
  #   steps:
  #     - name: ServiceNow DevOps Get Change
  #       # You may pin to the exact commit or the version.
  #       # uses: ServiceNow/servicenow-devops-get-change@0f8b1914adeaec764a4286bdd9cba73ed1c6097f
  #       uses: ServiceNow/servicenow-devops-get-change@dev
  #       id: get_change
  #       with:
  #         # ServiceNow Instance URL
  #         instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #         # Devops Integration Token
  #         # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
  #         devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
  #         devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
  #         # Orchestration Tool Id
  #         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #         # Github Context
  #         context-github: ${{ toJSON(github) }}
  #         # The inputs to identify change at Servicenow and GET it.
  #         change-details: '{"build_number":"","pipeline_name":"","stage_name":"deploy"}'
