name: SonarScanSummaryCustomTaskActions

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Java JDK for Sonar Cloud
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle'
          java-version: '17'
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
        
      - name: Sonar Cloud Analysis
        if: success() # always() failure() success()
        run: >
            mvn -B verify -DskipTests sonar:sonar
            -Dsonar.projectKey=$SONAR_PROJECT_KEY
            -Dsonar.organization=$SONAR_ORG_KEY
            -Dsonar.host.url=$SONAR_URL
            -Dsonar.login=$SONAR_TOKEN
        env:
          # GITHUB_TOKEN: '${{ secrets.GHP_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
          SONAR_PROJECT_KEY: '${{ secrets.SONAR_PROJECT_KEY }}'
          SONAR_URL: '${{ secrets.SONAR_URL }}'
          SONAR_ORG_KEY: '${{ secrets.SONAR_ORG_KEY }}'
      - name: ServiceNow DevOps Sonar Scan Results
        uses: ServiceNow/servicenow-devops-sonar@main
        with:
          instance-url: '${{ secrets.SN_INSTANCE_URL }}'
          devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
          devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
          tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
          context-github: '${{ toJSON(github) }}'
          job-name: Build
          sonar-host-url: '${{ secrets.SONAR_URL }}'
          sonar-project-key: '${{ secrets.SONAR_PROJECT_KEY }}'
