name: TestSummaryActionWithEnvironment

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:        
  integrationTest:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Run Maven Tests
        run: mvn --batch-mode --update-snapshots verify
