name: TestSummaryCustomAction

on:
  workflow_dispatch:

jobs:        
  integrationTest:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@main
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Integration Tests'
          test-summary-name: 'Automated Test Summery'
          xml-report-filename: target/surefire-reports/testng-results.xml

      # - name: ServiceNow DevOps NUnit Test Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # Job Name
      #     job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
      #     # Github Context
      #     context-github: ${{ toJSON(github) }}
      #      # XUnit xml report file name with path
      #     xml-report-filename: NUnitFolder/NUnit.xml  

      # - name: ServiceNow DevOps XUnit Test Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # Job Name
      #     job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
      #     # Github Context
      #     context-github: ${{ toJSON(github) }}
      #      # XUnit xml report file name with path
      #     xml-report-filename: XUnitFolder/Xunit.xml   

      # - name: ServiceNow DevOps Jest Test Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # Job Name
      #     job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
      #     # Github Context
      #     context-github: ${{ toJSON(github) }}
      #      # XUnit xml report file name with path
      #     xml-report-filename: JestFolder/jest-junit.xml    

      # - name: ServiceNow DevOps MSTest Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # Job Name
      #     job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
      #     # Github Context
      #     context-github: ${{ toJSON(github) }}
      #      # XUnit xml report file name with path
      #     xml-report-filename: MSTestFolder/MSTest.trx   

      # - name: ServiceNow DevOps CTest Results
      #   uses: ServiceNow/servicenow-devops-test-report@dev
      #   with:
      #     # devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
      #     # devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
      #     devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # Job Name
      #     job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
      #     # Github Context
      #     context-github: ${{ toJSON(github) }}
      #      # XUnit xml report file name with path
      #     xml-report-filename: CTestFolder/CTest.xml
  change:
    name: Change Request
    needs: integrationTest
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps Change Attributes
        uses: ServiceNow/servicenow-devops-change@main
        with:
          # devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          # devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Change Request'
          change-request: '{"autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployments","chg_model":"007c4001c343101035ae3f52c1d3aeb2","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed."}}'
          interval: '100'
          timeout: '3600'
