name: TestSummaryCustomAction

on:
  workflow_dispatch:

jobs:        
  integrationTest:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo Run integration tests.
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
        
      - name: ServiceNow DevOps Unit Test Result
        uses: ServiceNow/servicenow-devops-test-report@main
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Integration Tests'
          xml-report-filename: target/surefire-reports/testng-results.xml

      - name: ServiceNow DevOps NUnit Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_NAME }}
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          # Job Name
          job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
          # Github Context
          context-github: ${{ toJSON(github) }}
           # XUnit xml report file name with path
          xml-report-filename: NunitFolder/NUnit.xml   

      - name: ServiceNow DevOps XUnit Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_NAME }}
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          # Job Name
          job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
          # Github Context
          context-github: ${{ toJSON(github) }}
           # XUnit xml report file name with path
          xml-report-filename: XUnitFolder/Xunit.xml   

      - name: ServiceNow DevOps Jest Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_NAME }}
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          # Job Name
          job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
          # Github Context
          context-github: ${{ toJSON(github) }}
           # XUnit xml report file name with path
          xml-report-filename: JestFolder/jest-junit.xml    

      - name: ServiceNow DevOps MS Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_NAME }}
          tool-id: ${{ secrets.SN_ORCH_TOOL_ID }}
          # Job Name
          job-name: 'Integration Tests' # Should be same name as declared in 'name' clause of the current Stage
          # Github Context
          context-github: ${{ toJSON(github) }}
           # XUnit xml report file name with path
          xml-report-filename: MSTestFolder/MSTest.trx    
